import React from "react";

const surahs = [
  { english: "Al-Fatihah", urdu: "الفاتحہ" },
  { english: "Al-Baqarah", urdu: "البقرہ" },
  { english: "Aal-E-Imran", urdu: "آل عمران" },
  { english: "An-Nisa", urdu: "النساء" },
  { english: "Al-Maidah", urdu: "المائدہ" },
  { english: "Al-An'am", urdu: "الانعام" },
  { english: "Al-A'raf", urdu: "الاعراف" },
  { english: "Al-Anfal", urdu: "الانفال" },
  { english: "At-Tawbah", urdu: "التوبہ" },
  { english: "Yunus", urdu: "یونس" },
  { english: "Hud", urdu: "ہود" },
  { english: "Yusuf", urdu: "یوسف" },
  { english: "Ar-Ra'd", urdu: "الرعد" },
  { english: "Ibrahim", urdu: "ابراہیم" },
  { english: "Al-Hijr", urdu: "الحجر" },
  { english: "An-Nahl", urdu: "النحل" },
  { english: "Al-Isra", urdu: "الاسراء" },
  { english: "Al-Kahf", urdu: "الکہف" },
  { english: "Maryam", urdu: "مریم" },
  { english: "Ta-Ha", urdu: "طٰہٰ" },
  { english: "Al-Anbiya", urdu: "الانبیاء" },
  { english: "Al-Hajj", urdu: "الحج" },
  { english: "Al-Mu’minun", urdu: "المؤمنون" },
  { english: "An-Nur", urdu: "النور" },
  { english: "Al-Furqan", urdu: "الفرقان" },
  { english: "Ash-Shu’ara", urdu: "الشعراء" },
  { english: "An-Naml", urdu: "النمل" },
  { english: "Al-Qasas", urdu: "القصص" },
  { english: "Al-Ankabut", urdu: "العنکبوت" },
  { english: "Ar-Rum", urdu: "الروم" },
  { english: "Luqman", urdu: "لقمان" },
  { english: "As-Sajda", urdu: "السجدہ" },
  { english: "Al-Ahzab", urdu: "الاحزاب" },
  { english: "Saba", urdu: "سبا" },
  { english: "Fatir", urdu: "فاطر" },
  { english: "Ya-Sin", urdu: "یس" },
  { english: "As-Saffat", urdu: "الصافات" },
  { english: "Sad", urdu: "ص" },
  { english: "Az-Zumar", urdu: "الزمر" },
  { english: "Ghafir", urdu: "غافر" },
  { english: "Fussilat", urdu: "فصلت" },
  { english: "Ash-Shura", urdu: "الشوری" },
  { english: "Az-Zukhruf", urdu: "الزخرف" },
  { english: "Ad-Dukhan", urdu: "الدخان" },
  { english: "Al-Jathiya", urdu: "الجاثیہ" },
  { english: "Al-Ahqaf", urdu: "الاحقاف" },
  { english: "Muhammad", urdu: "محمد" },
  { english: "Al-Fath", urdu: "الفتح" },
  { english: "Al-Hujurat", urdu: "الحجرات" },
  { english: "Qaf", urdu: "ق" },
  { english: "Adh-Dhariyat", urdu: "الذاریات" },
  { english: "At-Tur", urdu: "الطور" },
  { english: "An-Najm", urdu: "النجم" },
  { english: "Al-Qamar", urdu: "القمر" },
  { english: "Ar-Rahman", urdu: "الرحمن" },
  { english: "Al-Waqia", urdu: "الواقعہ" },
  { english: "Al-Hadid", urdu: "الحدید" },
  { english: "Al-Mujadila", urdu: "المجادلہ" },
  { english: "Al-Hashr", urdu: "الحشر" },
  { english: "Al-Mumtahina", urdu: "الممتحنہ" },
  { english: "As-Saff", urdu: "الصف" },
  { english: "Al-Jumu'a", urdu: "الجمعہ" },
  { english: "Al-Munafiqun", urdu: "المنافقون" },
  { english: "At-Taghabun", urdu: "التغابن" },
  { english: "At-Talaq", urdu: "الطلاق" },
  { english: "At-Tahrim", urdu: "التحریم" },
  { english: "Al-Mulk", urdu: "الملک" },
  { english: "Al-Qalam", urdu: "القلم" },
  { english: "Al-Haqqa", urdu: "الحاقہ" },
  { english: "Al-Ma'arij", urdu: "المعارج" },
  { english: "Nuh", urdu: "نوح" },
  { english: "Al-Jinn", urdu: "الجن" },
  { english: "Al-Muzzammil", urdu: "المزمل" },
  { english: "Al-Muddaththir", urdu: "المدثر" },
  { english: "Al-Qiyama", urdu: "القیامہ" },
  { english: "Al-Insan", urdu: "الانسان" },
  { english: "Al-Mursalat", urdu: "المرسلات" },
  { english: "An-Naba", urdu: "النبأ" },
  { english: "An-Nazi'at", urdu: "النازعات" },
  { english: "Abasa", urdu: "عبس" },
  { english: "At-Takwir", urdu: "التکویر" },
  { english: "Al-Infitar", urdu: "الانفطار" },
  { english: "Al-Mutaffifin", urdu: "المطففین" },
  { english: "Al-Inshiqaq", urdu: "الانشقاق" },
  { english: "Al-Buruj", urdu: "البروج" },
  { english: "At-Tariq", urdu: "الطارق" },
  { english: "Al-A'la", urdu: "الاعلیٰ" },
  { english: "Al-Ghashiya", urdu: "الغاشیہ" },
  { english: "Al-Fajr", urdu: "الفجر" },
  { english: "Al-Balad", urdu: "البلد" },
  { english: "Ash-Shams", urdu: "الشمس" },
  { english: "Al-Lail", urdu: "اللیل" },
  { english: "Ad-Duha", urdu: "الضحیٰ" },
  { english: "Ash-Sharh", urdu: "الشرح" },
  { english: "At-Tin", urdu: "التین" },
  { english: "Al-Alaq", urdu: "العلق" },
  { english: "Al-Qadr", urdu: "القدر" },
  { english: "Al-Bayyina", urdu: "البینۃ" },
  { english: "Az-Zalzala", urdu: "الزلزال" },
  { english: "Al-Adiyat", urdu: "العادیات" },
  { english: "Al-Qaria", urdu: "القارعہ" },
  { english: "At-Takathur", urdu: "التکاثر" },
  { english: "Al-Asr", urdu: "العصر" },
  { english: "Al-Humaza", urdu: "الہمزہ" },
  { english: "Al-Fil", urdu: "الفیل" },
  { english: "Quraish", urdu: "قریش" },
  { english: "Al-Ma’un", urdu: "الماعون" },
  { english: "Al-Kawthar", urdu: "الکوثر" },
  { english: "Al-Kafirun", urdu: "الکافرون" },
  { english: "An-Nasr", urdu: "النصر" },
  { english: "Al-Lahab", urdu: "اللھب" },
  { english: "Al-Ikhlas", urdu: "الاخلاص" },
  { english: "Al-Falaq", urdu: "الفلق" },
  { english: "An-Nas", urdu: "الناس" },
];

const SelectSurah = ({ SurahName, setSurahName }) => {
  return (
    <div className="max-w-sm mx-auto">
      <select
        value={SurahName}
        onChange={(e) => setSurahName(e.target.value)}
        className="outline-none p-2 rounded-lg bg-black text-gray-100 focus:ring-2 focus:ring-gray-300"
      >
        <option value="" className="rounded-3xl font-semibold">Surah Name</option>
        {surahs.map((surah, index) => (
          <option key={index} value={surah.english}>
            {index + 1}. {surah.english} ({surah.urdu})
          </option>
        ))}
      </select>
    </div>
  );
};

export default SelectSurah;
